# Generated by Django 4.0 on 2021-12-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/0.jpeg', upload_to='static/avatar/%y/%m/%d', verbose_name='Аватар'),
        ),
    ]
