# Generated by Django 4.0 on 2021-12-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='profile_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='likeanswer',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='likeanswer',
            old_name='profile_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='likequestion',
            old_name='profile_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='likequestion',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='user'),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/0.jpeg', upload_to='static/avatar/%y/%m/%d', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_create'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislikes_count',
            field=models.IntegerField(default=0, verbose_name='dislikes_count'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='likes_count'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number_of_answers',
            field=models.IntegerField(default=0, verbose_name='number_of_answers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='app.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='title'),
        ),
        migrations.AlterUniqueTogether(
            name='likeanswer',
            unique_together={('answer', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='likequestion',
            unique_together={('question', 'author')},
        ),
    ]
