# Generated by Django 4.0 on 2021-12-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0003_rename_profile_id_answer_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='author',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='likeanswer',
            old_name='answer',
            new_name='answer_id',
        ),
        migrations.RenameField(
            model_name='likeanswer',
            old_name='author',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='likequestion',
            old_name='author',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='likequestion',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='question',
            name='profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/0.jpeg', upload_to='static/avatar/%y/%m/%d', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislikes_count',
            field=models.IntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number_of_answers',
            field=models.IntegerField(default=0, verbose_name='Количество ответов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='app.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Заголовок'),
        ),
        migrations.AlterUniqueTogether(
            name='likeanswer',
            unique_together={('answer_id', 'profile_id')},
        ),
        migrations.AlterUniqueTogether(
            name='likequestion',
            unique_together={('question_id', 'profile_id')},
        ),
    ]
